# Generated by Django 4.2.28 on 2026-02-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_delivered",
            field=models.BooleanField(default=False),
        ),
    ]
